import javax.swing.DefaultListModel;
import java.sql.*;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * OrderINUI.javaimport
 *
 * Created on Mar 17, 2010, 5:54:13 PM
 */

/**
 *
 * @author gagan
 */
public class OrderINUI extends javax.swing.JFrame {

    /** Creates new form OrderINUI */
    public OrderINUI() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel9 = new javax.swing.JLabel();
        txtOrdno = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnClear = new javax.swing.JButton();
        txtOrdDate = new javax.swing.JTextField();
        txtOrdQty = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtItemPrice = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtSID = new javax.swing.JTextField();
        txtSName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtItemID = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        jPanel1 = new javax.swing.JPanel();
        rdYes = new javax.swing.JRadioButton();
        rdNo = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        txtDisc = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Order Form");
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Order Quantity:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 110, -1));

        txtOrdno.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(txtOrdno, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 35, 62, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Date:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 38, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Shopper's Id and Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 79, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Item Id and Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 79, -1, -1));

        btnClear.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 427, 87, -1));

        txtOrdDate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(txtOrdDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 35, 170, -1));

        txtOrdQty.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(txtOrdQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 111, -1));

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBack.setText("Back to Main");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 427, 163, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setText("Sports Item Order Form");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 0, -1, -1));

        btnSave.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSave.setText("Save Order");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 427, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Order No.:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 38, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Item price:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, -1, -1));

        txtItemPrice.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(txtItemPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 290, 116, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("ID.:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Name:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));
        getContentPane().add(txtSID, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 156, -1));

        txtSName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSNameActionPerformed(evt);
            }
        });
        getContentPane().add(txtSName, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 220, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Item ID.:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, -1, -1));
        getContentPane().add(txtItemID, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 260, 116, -1));

        jList1.setModel(new DefaultListModel());
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 203, -1));

        jList2.setModel(new DefaultListModel());
        jList2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jList2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 100, 231, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Discount"));
        jPanel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        buttonGroup1.add(rdYes);
        rdYes.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        rdYes.setText("Yes");

        buttonGroup1.add(rdNo);
        rdNo.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        rdNo.setText("No");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rdYes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(rdNo)
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdYes)
                    .addComponent(rdNo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, -1, 60));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Discount (%):");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 390, -1, -1));

        txtDisc.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(txtDisc, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 390, 109, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1-2-long-handle-hitman-full-size-double-blade-poplar-cricket-bat-original-imaf9jhgtgnpkgag.jpeg"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        txtOrdno.setText("");
        txtOrdDate.setText("");
        txtSID.setText("");
        txtItemID.setText("");
        txtSName.setText("");
        txtItemPrice.setText("");
        txtOrdQty.setText("");
}//GEN-LAST:event_btnClearActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.setVisible(false);
        new MainMenuUI().setVisible(true);
}//GEN-LAST:event_btnBackActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        try {
            Class.forName("java.sql.Driver");
            Connection con =DriverManager.getConnection("jdbc:mysql://localhost:3306/sportsagency","root","ranjit");
            Statement stmt = null;
            ResultSet rs = null;   
            String SQL = "SELECT * FROM orderitem";
            stmt = con.createStatement();  
            rs = stmt.executeQuery(SQL);

            float discP = 0;
         
            String Ordno = txtOrdno.getText();
            String OrdDate = txtOrdDate.getText();
            String ItemID = txtItemID.getText();
            String ShopID = txtSID.getText();
            String ItemPrice = txtItemPrice.getText();
            double iPrice = Double.parseDouble(txtItemPrice.getText());
            String ordQty = txtOrdQty.getText();

            if (rdYes.isSelected()) {
                discP = Float.parseFloat(txtDisc.getText());
            }            else {
                discP=0;
            }

            double amt = (Integer.parseInt(txtOrdQty.getText()) * Double.parseDouble(txtItemPrice.getText())) - (Integer.parseInt(txtOrdQty.getText()) * Double.parseDouble(txtItemPrice.getText()))*(discP*0.01);
            String strSQL = "INSERT INTO orderitem(orderno, OrderDate, Item_Id, Shopper_Id, Quantity, price, discount, Amount ) VALUES ('"+(Ordno)+"','"+(OrdDate)+"','"+(ItemID)+"','"+(ShopID)+"',"+(ordQty)+","+iPrice+","+ discP+","+(amt)+")";
            JOptionPane.showMessageDialog(this, "Order successfully placed");
            int rowsEffected = stmt.executeUpdate(strSQL);
            System.out.println(rowsEffected + " rows effected");
            con.close();

         } catch (Exception e) {
             JOptionPane.showMessageDialog(this,e.getMessage());
        }
}//GEN-LAST:event_btnSaveActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus

        DefaultListModel sModel = (DefaultListModel) jList1.getModel();
        DefaultListModel iModel = (DefaultListModel) jList2.getModel();
        sModel.clear();
        iModel.clear();
        try {
            Class.forName("java.sql.Driver");
            Connection con =
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/sportsagency","root","ranjit");
            Statement stmt = null;
            ResultSet rs = null;
            ResultSet rs1 = null;
            String SQL = "SELECT * FROM shopkeeper";
            String SQL1 = "SELECT * FROM item";
            stmt = con.createStatement();
            rs = stmt.executeQuery(SQL);
            while (rs.next()) {
                String sID = rs.getString("Shopper_id");
                String Sname = rs.getString("Name");
                sModel.addElement(sID + " - " + Sname);
            }
            jList1.setModel(sModel);
            rs1 = stmt.executeQuery(SQL1);
            while (rs1.next()) {
                String iID = rs1.getString("Item_Id");
                String Iname = rs1.getString("Item_Name");
                iModel.addElement(iID + " - " + Iname);
            }
            jList2.setModel(iModel);
            con.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,e.getMessage());}

    }//GEN-LAST:event_formWindowGainedFocus

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked

            String SidName = (String) jList1.getSelectedValue();
            String Sid = SidName.substring(0,1);
            String Sname= SidName.substring(5);
            txtSID.setText(Sid);
            txtSName.setText(Sname);
    }//GEN-LAST:event_jList1MouseClicked

    private void jList2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList2MouseClicked
        try {
            Class.forName("java.sql.Driver");
            Connection con =
                 DriverManager.getConnection("jdbc:mysql://localhost:3306/sportsagency","root","ranjit");
            Statement stmt = null;
            ResultSet rs = null;
            String ItemIDName = (String) jList2.getSelectedValue();
            String ItemID = ItemIDName.substring(0,1);
            String Iame= ItemIDName.substring(0);
            txtItemID.setText(ItemID);
            String SQL = "SELECT * FROM item where Item_Id = '"+(ItemID)+"'";
            stmt = con.createStatement();
            rs = stmt.executeQuery(SQL);

            while (rs.next()) {
                double iprice = rs.getDouble("Price");
                txtItemPrice.setText(Double.toString(iprice));
            }
            con.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }

    }//GEN-LAST:event_jList2MouseClicked

    private void txtSNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSNameActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderINUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnSave;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1;
    private javax.swing.JList jList2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rdNo;
    private javax.swing.JRadioButton rdYes;
    private javax.swing.JTextField txtDisc;
    private javax.swing.JTextField txtItemID;
    private javax.swing.JTextField txtItemPrice;
    private javax.swing.JTextField txtOrdDate;
    private javax.swing.JTextField txtOrdQty;
    private javax.swing.JTextField txtOrdno;
    private javax.swing.JTextField txtSID;
    private javax.swing.JTextField txtSName;
    // End of variables declaration//GEN-END:variables

}
